name: Check PR Title
on:
    workflow_dispatch:
     inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true 
jobs:
  check:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
    - uses: deepakputhraya/action-pr-title@master
      with:
        regex: '^(feat|fix|breaking|build|chore|docs|style|refactor|test)\((kopiaui|cli|ui|repository|snapshots|server|providers|deps|deps-dev|site|ci|infra|general)\)!{0,1}: .*$'
